### ISSUE TITLE
Pick up config home from environment

### ISSUE THREAD

**Issue by fancsali** [skonfig/skonfig#49]
**Summary**

Similarly to hosw `cdist` would let the user to specify the config home by the `CDIST_PATH` environment variable, `skonfig` should allow a similar mechanism to allow the user to diverge from the hard-coded `~/.skonfig`.

**Rationale**

This would allow the user to have several completely isolated (think work vs. pet-project) repositories without any interference (e.g. completely different infrastructure would need the same `if`s all the time) or leakage of information (secrets and similar).

As an additional benefit the user could then leverage `skonfig`s feature to load further type libraries from the `set` sub-directory, allowing the user to add any dependencies of their project as git submodules to the repo in question.

**Implementation approach**
Probably we could compare the original `cdist` code with the current `skonfig` one, and use that as a guideline or even lift in some code.

**Comment by sideeffect42** [comment]
After going through the cdist code it seems that `~/.cdist` is hard coded as the place where you should store your `.cdist` repository, or did I miss something?

After thinking about it, I feel like this is not a terribly good decision.
Of course overriding the `CDIST_PATH` to use a different set of types is better than nothing but if you want to separate `$__files`, `$__manifest` it seems you're out of luck with cdist (and skonfig also).

Thinking of a service provider which might manage infrastructure for different clients it seems to me that it probably makes more sense to allow the user to overwrite the location of their `.skonfig` repository instead of just replacing the types.
With the `config` file now being part of a `.skonfig` repository a user could configure their `conf_path` (currently called `conf_dir`) per repository without needing to overwrite it using an environment variable.

In my case I'm currently managing two distinct sets of infrastructure with skonfig.
Since I use different computers to do so I never really had this problem, but if I were to consolidate these to a single computer overwriting the `conf_path` wouldn't suffice to me.

**Comment by fancsali** [comment]
I haven't had the time to look into the code, but certainly there's more to this than meets the eye. In fact, the migration to `skonfig` seems to be breaking my previous workflow in that it simply can't even find the initial manifest.

My previous workflow being:

- Having the **initial manifest** the **files** directory, and some **highly-specific types** in a git repo.
- Having my **personal reusable types** in another one
- Then checking out the former somewhere, let's say `$HOME/cdist-project-1` and the latter to e.g. `/opt/my-cdist-types`; perhaps even some types from others in `/opt/contrib-cdist-types`
- Then **exporting** `$CDIST_PATH=.:/opt/my-cdist-types:/opt/contrib-cdist-types` will let me simply `cd $HOME/cdist-project-1; cdist config ...`
- Then if I have another project in `$HOME/cdist-project-2`, simple doing `cd $HOME/cdist-project-2; cdist ...` would also work (due to the `.` in `CDIST_PATH`)

**NOTE**: This still works with the included **compatiblity** `cdist` binary, but won't find the manifest when calling `skonfig`.

Reinstating the above behaviour would also solve the issue with separating **files** from the **manifest**: simply have a list of directories in `CDIST_PATH`, one contains the files another one the manifest, and so on. Then one can even override types. As far as I understand, the first step in the config run is to merge the things in the different paths (different sets, users types, built in types, etc...) exactly for this reason.

So, I'd say, there's no need to engineer a complex solution here, just run with the stated goal of skonfig to be nice and simple, but lift this feature from the old cdist code.

But then again, there's a fair chance, I am missing something here, and it's not that simple after all...

**Comment by 4nd3r** [comment]
I think we should support `SKONFIG_HOME` envvar, which defaults to `~/.skonfig` and everything else depend on it.

Now, if we talk about `XDG_*` envvars, then this will get out of hand. Because working with `skonfig` means working with files in its configuration home, then hiding it to multiple places deep in `$HOME` doesn't sound like good idea. That directory must be quickly accessible and `cd .skonfig` is quick in my books.

Only directory, which we might want to move, is `~/.skonfig/dump` and use `~/.cache/skonfig` instead. But then again, why make things complicated? If you are running git inside `~/.skonfig`, then you can add `dump` to `.gitignore`.

Sure, XDG is nice standard and I wish more applications follow it, but...

`~/.config/skonfig/config`
`~/.local/share/skonfig/{type,set,explorer,...}/`
`~/.cache/skonfig/`

This feels bit too much.

**Comment by fancsali** [comment]
I have to agree.

Especially, that the `skonfig` code is not configuration in and of itself – it's not necessarily a piece of config that you'd carry with yourself in your `$HOME` between machines and systems; and only change very rarely.

I see it more like a software project – where the code isn't buried somewhere in a hidden directory but rather worked on regularly. And which is not exclusive in the sense, that I only have one fine-tuned setup for my desktop, but I do work on several projects at the same time.

So, while defaulting to `~/.skonfig` seems a safe and sensible safeguard, forcing the user to shoehorn everything into one single repo and essentially hide it as if it would be something that's not worked on but only changed once in a blue moon is rather limiting.

**Comment by 4nd3r** [comment]
#50 was merged and I'll start working on this.
